### ISSUE TITLE
I have problems when downloading the training datas of LSTM.

### ISSUE THREAD

**Issue by njhzqj** [bhattg/Decay-RNN-ACL-SRW2020#1]
When I click the download link, it just shows.

"404

File not found"

**Comment by Hritikbansal** [comment]
Hi! Thanks for your interest in this project.

The original repository for the dataset is https://github.com/TalLinzen/rnn_agreement. Please check if you can find it there. If not, it would be a better idea to open this issue on that repo.

**Comment by njhzqj** [comment]
Thanks for your comment! I have found that data.
